SETTING UP

In [ ]:
getwd()
setwd()

[1] "e:/data rush"

VECTORS

In [17]:
#num vector
age<-c(19,17,21,20,37)
age

#Char vector
name<-c("Luffy","Chopper","Zoro","Nami","Jinbe")
name

gender<-c('M',"M","M","F","M")
gender

#logic vec
gender_is_M<-c(TRUE,TRUE,TRUE,FALSE,TRUE)
gender_is_M

[1] 19 17 21 20 37

[1] "Luffy"   "Chopper" "Zoro"    "Nami"    "Jinbe"

[1] "M" "M" "M" "F" "M"

[1]  TRUE  TRUE  TRUE FALSE  TRUE

In [28]:
#classes and types class() typeof()

class(age) 
typeof(age)


[1] "numeric"

[1] "double"

In [ ]:
# Define a helper function to print class and type
print_class_type <- function(var, var_name) {
  cat("Class of", var_name, "=", class(var), ",", "Type of", var_name, "=", typeof(var), "\n") # nolint
}

# Use the function for each variable
print_class_type(age, "age")
print_class_type(name, "name")
print_class_type(gender, "gender")
print_class_type(gender_is_M, "gender_is_M")


Class of age = numeric , Type of age = double 
Class of name = character , Type of name = character 
Class of gender = character , Type of gender = character 
Class of gender_is_M = logical , Type of gender_is_M = logical 


In [24]:
print<-function(x){cat(x)}
print("Hello World")

Hello World

In [ ]:
#sequence start end
sequential <- seq(1,8)
sequential

##sequence start end steps
sequential1 <- seq(1,8,2)
sequential1

[1] 1 2 3 4 5 6 7 8

[1] 1 3 5 7

In [ ]:
#repeating

re <-rep(8,10)
re

re_str<-rep("yes",5)
re_str


[1] 8 8 8 8 8 8 8 8 8 8

[1] "yes" "yes" "yes" "yes" "yes"

[1] "Yes"

In [15]:
#random

rand<-runif(5)
rand

rand1<-runif(5,20,30)
rand1

round1 <-round(runif(5,20,30))
round1


[1] 0.07788027 0.63467956 0.96043111 0.46123914 0.08253471

[1] 28.38771 20.98586 25.62955 29.23205 29.60158

[1] 30 20 21 20 29

DATA FRAMES

In [19]:
df = data.frame(cbind(name,age,gender,gender_is_M))
df
fix(df)

name    age gender gender_is_M
1 Luffy   19  M      TRUE       
2 Chopper 17  M      TRUE       
3 Zoro    21  M      TRUE       
4 Nami    20  F      FALSE      
5 Jinbe   37  M      TRUE

In [ ]:
#inserted with fix() function
df

name    age gender gender_is_M
1 Luffy   19  M      TRUE       
2 Chopper 17  M      TRUE       
3 Zoro    21  M      TRUE       
4 Nami    20  F      FALSE      
5 Jinbe   37  M      TRUE       
6 Robin   32  F      FALSE      
7 Sanji   21  M      TRUE       
8 Brook   106 M      TRUE       
9 Ussop   19  M      TRUE

In [28]:
#specific elements of df

df$name
df$gender

#specific columns range
cat('Selective columns range')
df[1:3]

#specific columns
cat('Selective columns ')
df[c("name","gender")]


[1] "Luffy"   "Chopper" "Zoro"    "Nami"    "Jinbe"   "Robin"   "Sanji"  
[8] "Brook"   "Ussop"

[1] "M" "M" "M" "F" "M" "F" "M" "M" "M"

Selective columns range

name    age gender
1 Luffy   19  M     
2 Chopper 17  M     
3 Zoro    21  M     
4 Nami    20  F     
5 Jinbe   37  M     
6 Robin   32  F     
7 Sanji   21  M     
8 Brook   106 M     
9 Ussop   19  M

Selective columns 

name    gender
1 Luffy   M     
2 Chopper M     
3 Zoro    M     
4 Nami    F     
5 Jinbe   M     
6 Robin   F     
7 Sanji   M     
8 Brook   M     
9 Ussop   M

MATRIX AND ITS OPERATIONS

In [31]:
a <-matrix(1:8,nrow = 2,ncol = 4, byrow = TRUE,dimnames = list(c('I',"II"),c('w','x','y','z')))
a

w x y z
I  1 2 3 4
II 5 6 7 8

In [33]:
values = c(1,2,3,4,5,6,7,8)
matrix1 = matrix(values,nrow = 4,ncol = 2)
matrix1

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

In [ ]:
a[1,] #row index
a[,1] #col index

w x y z 
1 2 3 4

I II 
 1  5

In [ ]:
x = matrix(2:17,nrow = 4,ncol = 4,byrow = FALSE)
det(x) #determinant

[1] 0

In [51]:
y<-t(x) #transpose
y

[,1] [,2] [,3] [,4]
[1,]  2    3    4    5  
[2,]  6    7    8    9  
[3,] 10   11   12   13  
[4,] 14   15   16   17

In [54]:
x-y # matrix sub
x+y # matrix add

[,1] [,2] [,3] [,4]
[1,]  0    3    6   9   
[2,] -3    0    3   6   
[3,] -6   -3    0   3   
[4,] -9   -6   -3   0

[,1] [,2] [,3] [,4]
[1,]  4    9   14   19  
[2,]  9   14   19   24  
[3,] 14   19   24   29  
[4,] 19   24   29   34

In [ ]:
z = a%*%x # matrix mult
z

[,1] [,2] [,3] [,4]
I  40    80  120  160 
II 96   200  304  408

In [ ]:
eigen(x) #eigen values

eigen() decomposition
$values
[1]  4.000000e+01 -2.000000e+00  9.481761e-16 -2.366039e-16

$vectors
           [,1]          [,2]       [,3]        [,4]
[1,] -0.4223684 -8.164966e-01 -0.1648566  0.30885319
[2,] -0.4720588 -4.082483e-01  0.6091261 -0.07465138
[3,] -0.5217492  6.852613e-17 -0.7236824 -0.77725681
[4,] -0.5714396  4.082483e-01  0.2794129  0.54305500
